### ISSUE TITLE
responsive Layout error in signature page 

### ISSUE THREAD

**Issue by petedavis** [esitarski/RaceDB#1]
When the page snaps to a smaller device, the container with the scriptel link entirely covers the form with the other buttons and the user cannot click OK. I think you need to put the form inside the container, row and column  to ensure that it is laid out correctly.

![signon layout error](https://cloud.githubusercontent.com/assets/164331/16180926/9876dcba-36d1-11e6-8dce-c4d66e069bcc.png)

**Comment by esitarski** [comment]
Thanks for finding this Peter.
Sometimes Bootstrap's adaptive layout does unexpected things.
I will take a look.

On Sun, Jun 19, 2016 at 8:59 PM, Peter Davis <notifications@github.com>
wrote:

> When the page snaps to a smaller device, the container with the scriptel
> link entirely covers the form with the other buttons and the user cannot
> click OK. I think you need to put the form inside the container, row and
> column to ensure that it is laid out correctly.
>
> [image: signon layout error]
> <https://cloud.githubusercontent.com/assets/164331/16180926/9876dcba-36d1-11e6-8dce-c4d66e069bcc.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/esitarski/RaceDB/issues/1>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAJrqWeShd15jc50dB-arR5DqkppcdPWks5qNeYDgaJpZM4I5SsB>
> .
>



-- 

Edward Sitarski
Provincial Chief Commissaire of Ontario, Track Cycling

**Comment by petedavis** [comment]
I use bootstrap for all my web projects, although I am no designer I have a good handle on the layout. Containers will only push against other containers, rows against rows etc, so the container will layout in the same space as the form at the same level.

So just need to move form inside page layout divs so that it is contained within the responsive elements and not fighting with them.

**Comment by mbuckaway** [comment]
Closing old issue
