### ISSUE TITLE
RaceDB - startlist export as UCI DataRide Excel fails

### ISSUE THREAD

**Issue by stuartlynne** [esitarski/RaceDB#18]
Request Method: | GET
-- | --
http://192.168.40.16:8000/RaceDB/Competitions/CompetitionDashboard/367/StartList/978/UCIExcelDownload/978/0/
2.2.1
ValueError
seek of closed file
/lvm1/home/racedb/RaceDB-03000027/core/views.py in UCIExcelDownload, line 1401
/usr/bin/python3
3.6.8
['/lvm1/home/racedb/RaceDB-03000027',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 6 Jan 2020 00:44:00 -0800

**Comment by mbuckaway** [comment]
Fixed apparently.
