### ISSUE TITLE
RaceDb error TemplateDoesNotExist 

### ISSUE THREAD

**Issue by JFGiguere** [esitarski/RaceDB#47]
I've reinstall the computer, docker and RaceDB v3.0.84-20230327101343.
![RaceB Version](https://user-images.githubusercontent.com/105683592/230635162-cf2ceac3-4109-4b16-889f-84f08fe43f5b.png)

When i try to go on any page like competitions i got an error screen.
![competitions](https://user-images.githubusercontent.com/105683592/230635489-bf7b3b54-91f4-47f6-aea5-d94296330fb6.png)
 
same on teams and other pages
![image](https://user-images.githubusercontent.com/105683592/230635636-62590f88-7808-4879-9110-35ef387056aa.png)

**Comment by esitarski** [comment]
Should now be fixed in the latest release.

**Comment by JFGiguere** [comment]
I was able to make it work using image: esitarski/racedb:v3.0.82-20220801110523 as said in issue #44. I applied the update but with v3.0.84-20230501094927 it keeps restarting.

I tried a full clean install. Everything is working.

I’ll close issue 47.

De : Mark Buckaway ***@***.***>
Envoyé : 4 mai 2023 08:59
À : esitarski/RaceDB ***@***.***>
Cc : JFGiguere ***@***.***>; Mention ***@***.***>
Objet : Re: [esitarski/RaceDB] RaceDb error TemplateDoesNotExist (Issue #47)


@JFGiguere<https://github.com/JFGiguere> Please retest with the current release package, and close this issue if fixed.
