### ISSUE TITLE
RaceDB v3.0.84-20230501094927 Error in Category format and competitions

### ISSUE THREAD

**Issue by JFGiguere** [esitarski/RaceDB#48]
RaceDB v3.0.84-20230501094927

In category format when trying to add à new category i've got this error message:
![Capture d’écran 2023-05-13 095204](https://github.com/esitarski/RaceDB/assets/105683592/5afed49b-8732-4ac1-8415-ea6b11de4327)

In a competion, tryin to add à new mass star iv'e got this message:
![Capture d’écran 2023-05-13 094955](https://github.com/esitarski/RaceDB/assets/105683592/b2eb0259-b302-423c-b6b1-23c198af72d1)

**Comment by esitarski** [comment]
Fixed in latest version.
