### ISSUE TITLE
Feature Request - search of riders needing a license check

### ISSUE THREAD

**Issue by stuartlynne** [esitarski/RaceDB#71]
In the Competition Dashboard / Participants screen, can we get a search for License check? More specifically search for riders that have not had their license checked?

Also, in the search result table, can we get a new column for License Checked showing a blue tick or red X to show who has or has not had their license checked?

This would facilitate finding the people who have not had their license check done.

**Comment by esitarski** [comment]
Done.  Will be available in v3.0.99
