### ISSUE TITLE
Feature Request - See rider's Teams in Call-up

### ISSUE THREAD

**Issue by JFGiguere** [esitarski/RaceDB#72]
It would be great to have nearly the same info in Callups as in Start List. Officials often ask to have the riders teams on the callups sheet.

Is there an easy way to combine those information.

**Comment by esitarski** [comment]
Added Team and UCI ID to callups to be consistent with the start lists.

**Comment by JFGiguere** [comment]
It worked thank you

De : Edward Sitarski ***@***.***>
Envoyé : 2 juin 2024 08:45
À : esitarski/RaceDB ***@***.***>
Cc : JFGiguere ***@***.***>; Author ***@***.***>
Objet : Re: [esitarski/RaceDB] Feature Request - See rider's Teams in Call-up (Issue #72)


Added Team and UCI ID to callups to be consistent with the start lists.
